sudo: false
language: rust

cache:
  - cargo

install:
  - "script/bootstrap"
  
script:
  - "script/cibuild"

after_script:
  - "script/after_cibuild"
  
rust:
  - nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - texinfo
