sudo: false
language: rust

cache:
  - cargo

install:
  - "script/bootstrap"
  
script:
  - "script/cibuild"

after_script:
  - "script/after_cibuild"
  
rust:
  - nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - texinfo

notifications:
  email:
    on_success: never
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#jvm-rs"
    nick: jvm-rs-travis
    on_success: never
    on_failure: always
    use_notice: true
    skip_join: false
