[package]
name = "jvm-rs"
version = "0.1.0"
description = "JVM implemented in Rust, with an emphasis on performance and safety."
homepage = "https://github.com/shymega/jvm-rs"
repository = "https://github.com/shymega/jvm-rs.git"
keywords = ["jvm", "rust"]
readme= "README.md"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]

[dependencies]
